VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # CentOS
  config.vm.define :centos do |c|
    c.vm.box = "chef/centos-6.6"
    c.vm.hostname = "cenv"
    c.vm.network "private_network", ip: "192.168.50.70"
    c.vm.synced_folder ENV['HOME'], "/host"
    c.vm.synced_folder "provision/", "/provision"
    c.vm.provision "shell", inline: "/provision/install.sh"
  end

  config.vm.provider :virtualbox do |vm|
    vm.customize ["modifyvm", :id, "--memory", 4096]
    vm.customize ["modifyvm", :id, "--cpus", 1]
    vm.customize ["modifyvm", :id, "--cpuexecutioncap", "85"]
    vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end
